[Buttons]
CheckedSource=1
CheckedTranslation=0
Source=de, en
Translation=de, en

[CustomLanguages]
1\code=emj
1\id=15
1\iso639_1=
1\iso639_2=emj
1\name=Emoji
10\code=kmr
10\id=27
10\iso639_1=
10\iso639_2=kmr
10\name=Kurdish (Northern)
11\code=crs
11\id=11
11\iso639_1=
11\iso639_2=crs
11\name=Creole French (Seselwa)
12\code=zdj
12\id=2
12\iso639_1=
12\iso639_2=zdj
12\name=Comorian (Ngazidja)
13\code=acf
13\id=10
13\iso639_1=
13\iso639_2=acf
13\name=Creole French (Saint Lucian)
14\code=yua
14\id=41
14\iso639_1=
14\iso639_2=yua
14\name=Yucatec Maya
15\code=mrj
15\id=17
15\iso639_1=
15\iso639_2=mrj
15\name=Hill Mari
16\code=bjs
16\id=1
16\iso639_1=
16\iso639_2=bjs
16\name=Bajan
17\code=otq
17\id=32
17\iso639_1=
17\iso639_2=otq
17\name=Querétaro Otomi
18\code=tlh-Latn
18\id=24
18\iso639_1=
18\iso639_2=tlh
18\name=Klingon (Latin)
19\code=tet
19\id=36
19\iso639_1=
19\iso639_2=tet
19\name=Tetum
2\code=srn
2\id=33
2\iso639_1=
2\iso639_2=srn
2\name=Sranan Tongo
20\code=niu
20\id=30
20\iso639_1=
20\iso639_2=niu
20\name=Niuean
21\code=vic
21\id=9
21\iso639_1=
21\iso639_2=vic
21\name=Creole English (Virgin Islands)
22\code=pov
22\id=12
22\iso639_1=
22\iso639_2=pov
22\name=Creole Portuguese (Upper Guinea)
23\code=sjn
23\id=14
23\iso639_1=
23\iso639_2=sjn
23\name=Elvish (Sindarin)
24\code=gom
24\id=25
24\iso639_1=
24\iso639_2=gom
24\name=Konkani
25\code=hmn
25\id=18
25\iso639_1=
25\iso639_2=hmn
25\name=Hmong
26\code=syc
26\id=34
26\iso639_1=
26\iso639_2=syc
26\name=Syriac (Aramaic)
27\code=kri
27\id=26
27\iso639_1=
27\iso639_2=kri
27\name=Krio
28\code=ppk
28\id=38
28\iso639_1=
28\iso639_2=ppk
28\name=Uma
29\code=tmh
29\id=35
29\iso639_1=
29\iso639_2=tmh
29\name=Tamashek (Tuareg)
3\code=svc
3\id=8
3\iso639_1=
3\iso639_2=svc
3\name=Creole English (Vincentian)
30\code=bah
30\id=4
30\iso639_1=
30\iso639_2=bah
30\name=Creole English (Bahamas)
31\code=fn
31\id=16
31\iso639_1=fn
31\iso639_2=
31\name=Fanagalo
32\code=ikt
32\id=21
32\iso639_1=
32\iso639_2=ikt
32\name=Inuinnaqtun
33\code=gcl
33\id=5
33\iso639_1=
33\iso639_2=gcl
33\name=Creole English (Grenadian)
34\code=prs
34\id=13
34\iso639_1=
34\iso639_2=prs
34\name=Dari
35\code=udm
35\id=37
35\iso639_1=
35\iso639_2=udm
35\name=Udmurt
36\code=jw
36\id=22
36\iso639_1=jw
36\iso639_2=
36\name=Javanese
37\code=kazlat
37\id=23
37\iso639_1=
37\iso639_2=
37\name=Kazakh (Latin)
38\code=uzbcyr
38\id=39
38\iso639_1=
38\iso639_2=
38\name=Uzbek (Cyrillic)
39\code=lus
39\id=29
39\iso639_1=
39\iso639_2=lus
39\name=Mizo
4\code=jam
4\id=7
4\iso639_1=
4\iso639_2=jam
4\name=Creole English (Jamaican)
40\code=wls
40\id=40
40\iso639_1=
40\iso639_2=wls
40\name=Wallisian
41\code=ilo
41\id=20
41\iso639_1=
41\iso639_2=ilo
41\name=Ilocano
5\code=gyn
5\id=6
5\iso639_1=
5\iso639_2=gyn
5\name=Creole English (Guyanese)
6\code=mww
6\id=19
6\iso639_1=
6\iso639_2=mww
6\name=Hmong Daw
7\code=pot
7\id=31
7\iso639_1=
7\iso639_2=pot
7\name=Potawatomi
8\code=mhr
8\id=28
8\iso639_1=
8\iso639_2=mhr
8\name=Mari
9\code=aig
9\id=3
9\iso639_1=
9\iso639_2=aig
9\name=Creole English (Antigua and Barbuda)
size=41

[MainWindow]
AutoTranslate=false
ShowPrivacyPopup=false
WindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\x2\0\0\x4]\0\0\0\0\0\0\0\0\0\0\x3\x2\0\0\x4]\0\0\0\0\x2\0\0\0\x6@\0\0\0\0\0\0\0\0\0\0\x3\x2\0\0\x4])

[Translation]
Instance=https://mozhi.ducks.party
