foreground              #FFFFFF
background              #974C4E
selection_foreground    #974C4E
selection_background    #FFFFFF
cursor                  #1B1A29
cursor_text_color       #FFFFFF

active_tab_foreground     #974C4E
active_tab_background     #272E3C
inactive_tab_foreground   #272E3C
inactive_tab_background   #974C4E

# black
color0      #52292A
color8      #8F5759

# red
color1      #CFCCFF
color9      #AFAAF0

# green
color2      #CCF1FF
color10     #AADCF0

# yellow
color3      #CCDDFF
color11     #AAC1F0

# blue
color4      #E69A9C
color12     #E69A9C

# magenta
color5      #9AD0E6
color13     #9AD0E6

# cyan
color6      #9AB3E6
color14     #9AB3E6

# white
color7      #CFCCFF
color15     #AFAAF0
